version: "3.9"
services:
    app:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./:/var/www/html
    server:
        build:
            context: ./
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - '8080:80'
        volumes:
            -   ./:/var/www/html
